sudo: required

services:
    - docker

before_install:
    - docker build -t mydockerfrontend:latest -f ./z2/mydockerfrontend/Dockerfile.dev ./z2/mydockerfrontend

script:
    - docker run -e CI=true mydockerfrontend:latest yarn test
